# Generated by Django 3.2.11 on 2022-03-03 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='snippets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snippets',
            name='user_frontend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_frontend_snippets', to='flashcards.user_frontend'),
        ),
        migrations.AddField(
            model_name='flashcards',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_flashcards', to='flashcards.category'),
        ),
        migrations.AddField(
            model_name='flashcards',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_flashcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcards',
            name='user_frontend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_frontend_flashcards', to='flashcards.user_frontend'),
        ),
    ]
