# Generated by Django 3.2.11 on 2022-03-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20220325_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name_plural': 'Decks'},
        ),
    ]
